# Generated by Django 4.2.16 on 2024-12-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=150, null=True)),
                ('l_name', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subject', models.CharField(max_length=150)),
                ('teacher', models.ManyToManyField(to='attendence.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('f_name', models.CharField(max_length=150, null=True)),
                ('l_name', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('class_id', models.ManyToManyField(to='attendence.class')),
            ],
        ),
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('message', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(blank=True, max_length=250, null=True)),
                ('history', models.BooleanField(default=False)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendence.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ManyToManyField(to='attendence.subject'),
        ),
        migrations.CreateModel(
            name='Attendens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('attended_time', models.DateTimeField(blank=True, null=True)),
                ('missed_time', models.DateTimeField(blank=True, null=True)),
                ('timeout_time', models.DateTimeField(blank=True, null=True)),
                ('omad', models.BooleanField(default=False, null=True)),
                ('raft', models.BooleanField(default=False, null=True)),
                ('dercard', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendens', to='attendence.student')),
            ],
        ),
    ]
