# Generated by Django 3.2.23 on 2024-12-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='history',
        ),
        migrations.RemoveField(
            model_name='sendmessage',
            name='sent_by',
        ),
        migrations.AddField(
            model_name='attendens',
            name='is_late',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
