# Generated by Django 4.2.16 on 2024-12-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20241203_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendens',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
