# Generated by Django 4.2.16 on 2024-12-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_alter_sendmessage_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='chat_id',
            field=models.CharField(max_length=250),
        ),
    ]
