# Generated by Django 4.2.16 on 2024-12-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_auto_20241204_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('sent_to_groups', models.ManyToManyField(blank=True, to='attendence.telegramgroup', verbose_name='Отправлено в группы')),
            ],
            options={
                'verbose_name': 'Массовое сообщение',
                'verbose_name_plural': 'Массовые сообщения',
                'ordering': ['-created_at'],
            },
        ),
    ]
