# Generated by Django 4.2.16 on 2024-12-04 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0005_broadcastmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=150, unique=True)),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendence.class')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ManyToManyField(default=1, to='attendence.class'),
        ),
        migrations.DeleteModel(
            name='BroadcastMessage',
        ),
    ]
