# Generated by Django 4.2.16 on 2024-12-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0006_telegramgroup2_alter_student_class_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ManyToManyField(to='attendence.class'),
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.student')),
            ],
            options={
                'db_table': 'attendence_student_class',
            },
        ),
    ]
