# Generated by Django 3.2.23 on 2024-12-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0007_alter_student_class_id_studentclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendmessage',
            options={'ordering': ['-time'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='sendmessage',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='all_groups',
            field=models.BooleanField(default=False, help_text='Отправить всем группам'),
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='messages', to='attendence.TelegramGroup'),
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
