# Generated by Django 3.2.23 on 2024-12-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0008_auto_20241205_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='messages', to='attendence.TelegramGroup2'),
        ),
    ]
